server:
  url: "http://localhost"
  port: 80
  servlet:
    encoding:
      force-response: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  elasticsearch:
#    uris: http://localhost:9200
#    username: elastic
#    password: elastic

  jwt:
    secret: ${LOCAL_JWT_SECRET}

  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${LOCAL_CLIENT_ID_GOOGLE}
            client-secret: ${LOCAL_CLIENT_SECRET_GOOGLE}
            scope:
              - email
              - profile
          naver:
            client-id: ${LOCAL_CLIENT_ID_NAVER}
            client-secret: ${LOCAL_CLIENT_SECRET_NAVER}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:80/login/oauth2/code/naver

          kakao:
            client-id: ${LOCAL_CLIENT_ID_KAKAO}
            client-secret: ${LOCAL_CLIENT_SECRET_KAKAO}
            redirect-uri: http://localhost:80/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - account_email
              - profile_nickname

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json 으로 받는데 response 라는 키 값으로 네이버가 리턴해줌
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
